import assert from 'node:assert/strict';
import { runMobileCdpTest, technicianFixtureExpression, responsiveAuditExpression } from './helpers/mobile_browser_harness.mjs';
const {result,errors} = await runMobileCdpTest({name:'audit-completion',cdpPort:9368,run:async ({navigate,evaluate,setViewport,click,waitFor}) => {
  const results=[];
  await navigate('?audit-completion');
  for(const width of [360,390,430]) {
    await setViewport({width,height:844});
    await evaluate(technicianFixtureExpression({role:'technicien',started:true}));
    const layout=await evaluate(responsiveAuditExpression());
    assert.equal(layout.viewportWidth,width,'the actual DOM viewport must match the requested device');
    assert.equal(layout.globalOverflow,false);
    assert.equal(layout.buttonsAccessible,true);
    assert.equal(layout.dockVisible,true);
    assert.equal(layout.fixedBarsDoNotOverlap,true);
    const mainActions=await evaluate(`Array.from(document.querySelectorAll('#technician-field-action-dock > button')).map(b=>b.textContent.trim())`);
    assert.equal(mainActions.length,2,'two primary actions without horizontal scrolling');
    results.push({width,mainActions});
  }
  await setViewport({width:390,height:844});
  await evaluate(technicianFixtureExpression({role:'reception',started:false}));
  await evaluate(`setActiveTab('today'); renderTodayWorkshop();`);
  assert.equal(await evaluate(`document.querySelectorAll('#workshop-progress-board [data-workshop-progress-case]').length`),2);
  await click('#workshop-progress-board [data-workshop-progress-case]');
  await waitFor(`document.querySelector('#operational-case-dialog')?.open`,'context panel');
  await evaluate(`document.querySelector('#operational-case-dialog details:has([data-client-followup])').open=true;`);
  await evaluate(`(() => { const f=document.querySelector('[data-client-followup]'); f.elements.promisedAt.value='2026-09-08T16:00'; f.elements.nextContactAt.value='2026-09-07T10:00'; f.elements.note.value='Promesse confirmée par téléphone'; f.requestSubmit(); })()`);
  await waitFor(`state.cases.some(c=>c.clientCommitment?.note==='Promesse confirmée par téléphone')`,'followup persisted');
  await waitFor(`document.querySelector('#operational-case-dialog')?.open && document.querySelector('#operational-case-dialog .client-situation')?.textContent.includes('Promesse confirmée par téléphone')`,'updated panel after durable save');
  assert.match(await evaluate(`document.querySelector('#operational-case-dialog').textContent`),/Promesse confirmée par téléphone/);
  await click('#operational-case-dialog [data-close]');
  await evaluate(`state.cases[0].flags.workCompleted=true; state.bookings[0].status='completed'; state.bookings[0].remainingMinutes=0; state.currentUserId=state.users[0].id; state.users[0].role='controle_qualite'; invalidateUiRuntimeIndexes(); setActiveTab('today'); render();`);
  assert.equal(await evaluate(`document.querySelectorAll('#workshop-progress-board [data-workshop-progress-case]').length`),1,'CQ only sees its finalization queue');
  await click('#workshop-progress-board [data-workshop-progress-case]');
  await click('[data-operational-action="quality"]');
  await waitFor(`!document.querySelector('#custom-modal-overlay').hidden`,'quality confirmation');
  assert.equal(await evaluate(`document.querySelector('#operational-case-dialog').contains(document.querySelector('#custom-modal-overlay'))`),true,'confirmation remains above the native dialog');
  await click('#custom-modal-confirm');
  await waitFor(`state.cases[0].flags.qualityApproved===true`,'QC decision');
  await waitFor(`document.querySelector('#operational-case-dialog [data-operational-action="quality"]')===null`,'durable quality decision rendered before the next user takes over');
  assert.equal(await evaluate(`document.querySelector('#operational-case-dialog [data-operational-action="deliver"]')===null`),true);
  await click('#operational-case-dialog [data-close]');
  assert.equal(await evaluate(`document.querySelector('#custom-modal-overlay') !== null`),true,'closing a panel must preserve the shared confirmation dialog');
  await evaluate(`state.users[0].role='reception'; setActiveTab('today'); render();`);
  await click('#workshop-progress-board [data-workshop-progress-case="case-mobile-current"]');
  await click('[data-operational-action="deliver"]'); await click('#custom-modal-confirm');
  await waitFor(`state.cases[0].flags.delivered===true`,'physical handover');
  await click('#operational-case-dialog [data-close]');
  await waitFor(`document.querySelectorAll('#workshop-progress-board [data-workshop-progress-case="case-mobile-current"]').length===0`,'confirmed handover reflected in the board after durable save');
  assert.equal(await evaluate(`document.querySelectorAll('#workshop-progress-board [data-workshop-progress-case="case-mobile-current"]').length`),0);
  await evaluate(`setActiveTab('reception-workspace'); document.querySelector('.minimal-case-entry').open=true;`);
  await evaluate(`(() => {const f=document.querySelector('#minimal-case-form'); f.elements.identity.value='999TU999';f.elements.visitReason.value='Diagnostic freinage'; f.requestSubmit();})()`);
  await waitFor(`state.cases.some(c=>c.plate==='999TU999')`,'arrival without PDF');
  assert.equal(await evaluate(`state.cases.find(c=>c.plate==='999TU999').claims[0].clientApproved`),false);
  return results;
}});
assert.deepEqual(errors,[],'no browser errors');
console.log('AUDIT BROWSER PASS',JSON.stringify(result));
